version: "3.7"

services:
  app:
    build: .
    environment:
      - DB_HOST=db-service
      - DB_USERNAME=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=mydb
      - DB_PORT=3306
    networks:
      - my_network
    depends_on:
      - db-service

  db-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb
    ports:
      - "3307:3306"
    volumes:
      - /home/putridia/minipyvolume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2m
      timeout: 5s
      retries: 10
    networks:
      - my_network

networks:
  my_network:
    driver: bridge