version: "3.7"

services:
  app-service:
    build: .
    environment:
      - DB_HOST=database-service
      - DB_PORT=3307
      - DB_USERNAME=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=mydatabase
    networks:
      - my-network
    depends_on:
      database-service:
        condition: service_healthy
        restart: true

  database-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3307:3307"
    volumes:
      - /home/pdl/minipyvolume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 5s
      retries: 10
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
